[[services]]
  internal_port = 8889
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8554
  protocol = "tcp"
  [[services.ports]]
    port = 8554
