app = 'qcam'
primary_region = 'iad'

[build]

[[services]]
  internal_port = 8889
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]

[[services]]
  internal_port = 8554
  protocol = "tcp"
  [[services.ports]]
    port = 8554

[env]
  MTX_PATHS_ALL_SOURCE = "publisher"
  MTX_RTSP_PROTOCOLS = "tcp"
